port: 7890
allow-lan: true
mode: rule
log-level: info
proxies:
  - name: "Node_01"
    type: tuic
    server: ip1.758733.xyz
    port: 10088
    uuid: 9bbd1f42-7ae7-4239-bd10-a68de95e3295
    password: dongtaiwang.com
    username: 9bbd1f42-7ae7-4239-bd10-a68de95e3295
    alpn: [h3]
    reduce-rtt: true
  - name: "Node_02"
    type: tuic
    server: ip1.758733.xyz
    port: 10088
    uuid: 9bbd1f42-7ae7-4239-bd10-a68de95e3295
    password: dongtaiwang.com
    username: 9bbd1f42-7ae7-4239-bd10-a68de95e3295
    alpn: [h3]
    reduce-rtt: true
  - name: "Node_03"
    type: tuic
    server: 163.172.116.154
    port: 33887
    uuid: 9adb384a-0f16-4501-a8f3-b6b2556fce87
    password: dongtaiwang.com
    username: 9adb384a-0f16-4501-a8f3-b6b2556fce87
    alpn: [h3]
    reduce-rtt: true
  - name: "Node_04"
    type: tuic
    server: 157.254.223.24
    port: 41122
    uuid: 2aec7bfd-4178-4ee5-9bc5-fe4c241fdc15
    password: 2aec7bfd-4178-4ee5-9bc5-fe4c241fdc15
    username: 2aec7bfd-4178-4ee5-9bc5-fe4c241fdc15
    alpn: [h3]
    reduce-rtt: true
  - name: "Node_05"
    type: tuic
    server: 157.254.223.24
    port: 41122
    uuid: 2aec7bfd-4178-4ee5-9bc5-fe4c241fdc15
    password: 2aec7bfd-4178-4ee5-9bc5-fe4c241fdc15
    username: 2aec7bfd-4178-4ee5-9bc5-fe4c241fdc15
    alpn: [h3]
    reduce-rtt: true
  - name: "Node_06"
    type: tuic
    server: 157.254.223.48
    port: 11540
    uuid: 6845cb43-4b8d-49e8-a011-1051d6c4d2ae
    password: 6845cb43-4b8d-49e8-a011-1051d6c4d2ae
    username: 6845cb43-4b8d-49e8-a011-1051d6c4d2ae
    alpn: [h3]
    reduce-rtt: true
  - name: "Node_07"
    type: tuic
    server: 157.254.223.48
    port: 11540
    uuid: 6845cb43-4b8d-49e8-a011-1051d6c4d2ae
    password: 6845cb43-4b8d-49e8-a011-1051d6c4d2ae
    username: 6845cb43-4b8d-49e8-a011-1051d6c4d2ae
    alpn: [h3]
    reduce-rtt: true
  - name: "Node_08"
    type: hysteria
    server: 2a14:7584:d097::a
    port: 54177
    auth-str: dongtaiwang.com
    sni: apple.com
    skip-cert-verify: true
    alpn: [h3]
    protocol: udp
    up: "11 Mbps"
    down: "55 Mbps"
  - name: "Node_09"
    type: hysteria
    server: 2a14:7584:d097::a
    port: 54177
    auth-str: dongtaiwang.com
    sni: apple.com
    skip-cert-verify: true
    alpn: [h3]
    protocol: udp
    up: "11 Mbps"
    down: "55 Mbps"
  - name: "Node_10"
    type: hysteria
    server: 2a14:7584:d097::a
    port: 54177
    auth-str: dongtaiwang.com
    sni: apple.com
    skip-cert-verify: true
    alpn: [h3]
    protocol: udp
    up: "11 Mbps"
    down: "55 Mbps"
  - name: "Node_11"
    type: hysteria
    server: 2a14:7584:d097::a
    port: 54177
    auth-str: dongtaiwang.com
    sni: apple.com
    skip-cert-verify: true
    alpn: [h3]
    protocol: udp
    up: "11 Mbps"
    down: "55 Mbps"

proxy-groups:
  - name: 🚀 节点选择
    type: select
    proxies:
      - "Node_01"
      - "Node_02"
      - "Node_03"
      - "Node_04"
      - "Node_05"
      - "Node_06"
      - "Node_07"
      - "Node_08"
      - "Node_09"
      - "Node_10"
      - "Node_11"
      - DIRECT

rules:
  - DOMAIN-SUFFIX,google.com,🚀 节点选择
  - MATCH,🚀 节点选择