port: 7890
allow-lan: true
mode: rule
log-level: info
proxies:
  - name: "Node_01"
    type: hysteria
    server: 62.210.70.191
    port: 23556
    auth-str: github.com/Alvin9999-newpac/fanqiang
    sni: bing.com
    skip-cert-verify: true
    alpn: [h3]
    protocol: udp
    up: "11 Mbps"
    down: "55 Mbps"
  - name: "Node_02"
    type: hysteria
    server: 62.210.70.191
    port: 23556
    auth-str: github.com/Alvin9999-newpac/fanqiang
    sni: bing.com
    skip-cert-verify: true
    alpn: [h3]
    protocol: udp
    up: "11 Mbps"
    down: "55 Mbps"
  - name: "Node_03"
    type: hysteria
    server: 62.210.70.191
    port: 23556
    auth-str: github.com/Alvin9999-newpac/fanqiang
    sni: bing.com
    skip-cert-verify: true
    alpn: [h3]
    protocol: udp
    up: "11 Mbps"
    down: "55 Mbps"
  - name: "Node_04"
    type: hysteria
    server: 62.210.70.191
    port: 23556
    auth-str: github.com/Alvin9999-newpac/fanqiang
    sni: bing.com
    skip-cert-verify: true
    alpn: [h3]
    protocol: udp
    up: "11 Mbps"
    down: "55 Mbps"
  - name: "Node_05"
    type: select
    server: None
    port: None
  - name: "Node_06"
    type: hysteria
    server: 62.210.70.191
    port: 23556
    auth-str: github.com/Alvin9999-newpac/fanqiang
    sni: bing.com
    skip-cert-verify: true
    alpn: [h3]
    protocol: udp
    up: "11 Mbps"
    down: "55 Mbps"
  - name: "Node_07"
    type: hysteria
    server: 62.210.70.191
    port: 23556
    auth-str: github.com/Alvin9999-newpac/fanqiang
    sni: bing.com
    skip-cert-verify: true
    alpn: [h3]
    protocol: udp
    up: "11 Mbps"
    down: "55 Mbps"
  - name: "Node_08"
    type: hysteria
    server: 2a14:7584:d097::a
    port: 54177
    auth-str: dongtaiwang.com
    sni: apple.com
    skip-cert-verify: true
    alpn: [h3]
    protocol: udp
    up: "11 Mbps"
    down: "55 Mbps"
  - name: "Node_09"
    type: hysteria
    server: 2a14:7584:d097::a
    port: 54177
    auth-str: dongtaiwang.com
    sni: apple.com
    skip-cert-verify: true
    alpn: [h3]
    protocol: udp
    up: "11 Mbps"
    down: "55 Mbps"
  - name: "Node_10"
    type: hysteria
    server: 2a14:7584:d097::a
    port: 54177
    auth-str: dongtaiwang.com
    sni: apple.com
    skip-cert-verify: true
    alpn: [h3]
    protocol: udp
    up: "11 Mbps"
    down: "55 Mbps"
  - name: "Node_11"
    type: hysteria
    server: 2a14:7584:d097::a
    port: 54177
    auth-str: dongtaiwang.com
    sni: apple.com
    skip-cert-verify: true
    alpn: [h3]
    protocol: udp
    up: "11 Mbps"
    down: "55 Mbps"

proxy-groups:
  - name: 🚀 节点选择
    type: select
    proxies:
      - "Node_01"
      - "Node_02"
      - "Node_03"
      - "Node_04"
      - "Node_05"
      - "Node_06"
      - "Node_07"
      - "Node_08"
      - "Node_09"
      - "Node_10"
      - "Node_11"
      - DIRECT

rules:
  - DOMAIN-SUFFIX,google.com,🚀 节点选择
  - MATCH,🚀 节点选择